# Generated by Django 5.1.5 on 2025-01-29 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Predio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('edad', models.PositiveIntegerField()),
                ('identificacion', models.CharField(max_length=255)),
                ('procedencia', models.CharField(max_length=255)),
                ('antiguedad', models.PositiveIntegerField()),
                ('acceso_salud', models.CharField(max_length=255)),
                ('ocupacion', models.CharField(max_length=255)),
                ('cultivo_animales', models.BooleanField(default=False)),
                ('atractivo_ecoturistico', models.BooleanField(default=False)),
                ('colaboracion', models.TextField(blank=True, null=True)),
                ('fuente_agua', models.CharField(max_length=255)),
                ('foto_predio', models.URLField(blank=True, db_column='foto_predio', max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=255, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('correo', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=255)),
                ('rol_usuario', models.CharField(choices=[('Administrador', 'Administrador'), ('Usuario', 'Usuario')], max_length=20)),
                ('contraseña', models.CharField(max_length=255)),
            ],
        ),
    ]
